### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pagerduty#2]
Hi @lukewaite  

Are you still interested in maintaining this package?

If so, could we add support for laravel 5.5+ and 6.0?

Thanks!

**Comment by lukewaite** [comment]
👍 Can do, @atymic.

**Comment by atymic** [comment]
Thanks 😄

**Comment by atymic** [comment]
No worries, thanks!

Let me know if you need a hand

**Comment by atymic** [comment]
PR open for L6 here:
https://github.com/laravel-notification-channels/pagerduty/pull/3
