### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/pagerduty#7]
Laravel 8 has been released today and we need to update this repo to support it.
See https://laravel.com/docs/8.x/upgrade & https://github.com/laravel-notification-channels/channels/issues/107

**Comment by ilvalerione** [comment]
Is there someone to merge the Pull Request?

**Comment by atymic** [comment]
Sorry, thanks for the ping. Closed in #10

**Comment by ilvalerione** [comment]
Hi @atymic, you should also create a new release to have the updates in composer.

**Comment by atymic** [comment]
Thanks, done
